project:
  type: website
  output-dir: "docs"

website:
  title: "Ade Analytics"
  navbar: 
    left: 
      - text: "Home"
        file:  index.qmd
      - text: "Portfolio"
        file:  portfolio.qmd
      - text: "Tidy Tuesday"
        file:  tidy.qmd
      - text: "Viz Hub"
        file:  viz.qmd
      - text: "Shiny Apps"
        file:  Shiny projects.qmd
      - text: "CV"
        file:  CV.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cyborg
    css: styles.css

editor: visual

